// flow-typed signature: 5b9f346eb3c677520d3226e2b8d8953a
// flow-typed version: <<STUB>>/fastify-blipp_v1.2.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fastify-blipp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fastify-blipp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fastify-blipp/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fastify-blipp/src/index.js' {
  declare module.exports: $Exports<'fastify-blipp/src/index'>;
}
