// flow-typed signature: 7c327fa6f3dd8a14f1384594dd4a73aa
// flow-typed version: <<STUB>>/fastify-compress_v0.6.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fastify-compress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fastify-compress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fastify-compress/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fastify-compress/index' {
  declare module.exports: $Exports<'fastify-compress'>;
}
declare module 'fastify-compress/index.js' {
  declare module.exports: $Exports<'fastify-compress'>;
}
declare module 'fastify-compress/test.js' {
  declare module.exports: $Exports<'fastify-compress/test'>;
}
