// flow-typed signature: 7de228a11d9cdf61e2c6391b0595c468
// flow-typed version: <<STUB>>/fastify_v1.9.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fastify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fastify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fastify/examples/asyncawait' {
  declare module.exports: any;
}

declare module 'fastify/examples/example' {
  declare module.exports: any;
}

declare module 'fastify/examples/hooks-benchmark-async-await' {
  declare module.exports: any;
}

declare module 'fastify/examples/hooks-benchmark' {
  declare module.exports: any;
}

declare module 'fastify/examples/hooks' {
  declare module.exports: any;
}

declare module 'fastify/examples/http2' {
  declare module.exports: any;
}

declare module 'fastify/examples/https' {
  declare module.exports: any;
}

declare module 'fastify/examples/middleware' {
  declare module.exports: any;
}

declare module 'fastify/examples/parser' {
  declare module.exports: any;
}

declare module 'fastify/examples/plugin' {
  declare module.exports: any;
}

declare module 'fastify/examples/route-prefix' {
  declare module.exports: any;
}

declare module 'fastify/examples/simple' {
  declare module.exports: any;
}

declare module 'fastify/examples/use-plugin' {
  declare module.exports: any;
}

declare module 'fastify/fastify' {
  declare module.exports: any;
}

declare module 'fastify/lib/ContentTypeParser' {
  declare module.exports: any;
}

declare module 'fastify/lib/decorate' {
  declare module.exports: any;
}

declare module 'fastify/lib/handleRequest' {
  declare module.exports: any;
}

declare module 'fastify/lib/hookRunner' {
  declare module.exports: any;
}

declare module 'fastify/lib/hooks' {
  declare module.exports: any;
}

declare module 'fastify/lib/logger' {
  declare module.exports: any;
}

declare module 'fastify/lib/pluginUtils' {
  declare module.exports: any;
}

declare module 'fastify/lib/reply' {
  declare module.exports: any;
}

declare module 'fastify/lib/request' {
  declare module.exports: any;
}

declare module 'fastify/lib/schemas' {
  declare module.exports: any;
}

declare module 'fastify/lib/validation' {
  declare module.exports: any;
}

declare module 'fastify/test/404s.test' {
  declare module.exports: any;
}

declare module 'fastify/test/500s.test' {
  declare module.exports: any;
}

declare module 'fastify/test/async-await' {
  declare module.exports: any;
}

declare module 'fastify/test/async-await.test' {
  declare module.exports: any;
}

declare module 'fastify/test/beforeHandler.test' {
  declare module.exports: any;
}

declare module 'fastify/test/bodyLimit.test' {
  declare module.exports: any;
}

declare module 'fastify/test/case-insensitive.test' {
  declare module.exports: any;
}

declare module 'fastify/test/chainable.test' {
  declare module.exports: any;
}

declare module 'fastify/test/close-pipelining.test' {
  declare module.exports: any;
}

declare module 'fastify/test/close.test' {
  declare module.exports: any;
}

declare module 'fastify/test/context-config.test' {
  declare module.exports: any;
}

declare module 'fastify/test/custom-http-server.test' {
  declare module.exports: any;
}

declare module 'fastify/test/custom-parser-async' {
  declare module.exports: any;
}

declare module 'fastify/test/custom-parser.test' {
  declare module.exports: any;
}

declare module 'fastify/test/decorator.test' {
  declare module.exports: any;
}

declare module 'fastify/test/delete.test' {
  declare module.exports: any;
}

declare module 'fastify/test/error-in-post' {
  declare module.exports: any;
}

declare module 'fastify/test/fastify-instance.test' {
  declare module.exports: any;
}

declare module 'fastify/test/get.test' {
  declare module.exports: any;
}

declare module 'fastify/test/handler-context.test' {
  declare module.exports: any;
}

declare module 'fastify/test/head.test' {
  declare module.exports: any;
}

declare module 'fastify/test/helper' {
  declare module.exports: any;
}

declare module 'fastify/test/hooks-async' {
  declare module.exports: any;
}

declare module 'fastify/test/hooks.test' {
  declare module.exports: any;
}

declare module 'fastify/test/http2/http2.test' {
  declare module.exports: any;
}

declare module 'fastify/test/http2/plain' {
  declare module.exports: any;
}

declare module 'fastify/test/http2/secure-with-fallback' {
  declare module.exports: any;
}

declare module 'fastify/test/http2/secure' {
  declare module.exports: any;
}

declare module 'fastify/test/http2/unknwon-http-method' {
  declare module.exports: any;
}

declare module 'fastify/test/https/custom-https-server.test' {
  declare module.exports: any;
}

declare module 'fastify/test/https/https.test' {
  declare module.exports: any;
}

declare module 'fastify/test/inject.test' {
  declare module.exports: any;
}

declare module 'fastify/test/input-validation' {
  declare module.exports: any;
}

declare module 'fastify/test/input-validation.test' {
  declare module.exports: any;
}

declare module 'fastify/test/internals/all.test' {
  declare module.exports: any;
}

declare module 'fastify/test/internals/decorator.test' {
  declare module.exports: any;
}

declare module 'fastify/test/internals/handleRequest.test' {
  declare module.exports: any;
}

declare module 'fastify/test/internals/hookRunner.test' {
  declare module.exports: any;
}

declare module 'fastify/test/internals/hooks.test' {
  declare module.exports: any;
}

declare module 'fastify/test/internals/logger.test' {
  declare module.exports: any;
}

declare module 'fastify/test/internals/plugin.test' {
  declare module.exports: any;
}

declare module 'fastify/test/internals/reply.test' {
  declare module.exports: any;
}

declare module 'fastify/test/internals/validation.test' {
  declare module.exports: any;
}

declare module 'fastify/test/listen.test' {
  declare module.exports: any;
}

declare module 'fastify/test/logger.test' {
  declare module.exports: any;
}

declare module 'fastify/test/middleware.test' {
  declare module.exports: any;
}

declare module 'fastify/test/options.test' {
  declare module.exports: any;
}

declare module 'fastify/test/output-validation.test' {
  declare module.exports: any;
}

declare module 'fastify/test/patch.test' {
  declare module.exports: any;
}

declare module 'fastify/test/plugin.helper' {
  declare module.exports: any;
}

declare module 'fastify/test/plugin.test' {
  declare module.exports: any;
}

declare module 'fastify/test/post.test' {
  declare module.exports: any;
}

declare module 'fastify/test/pretty-print.test' {
  declare module.exports: any;
}

declare module 'fastify/test/promises.test' {
  declare module.exports: any;
}

declare module 'fastify/test/put.test' {
  declare module.exports: any;
}

declare module 'fastify/test/register.test' {
  declare module.exports: any;
}

declare module 'fastify/test/reply-error.test' {
  declare module.exports: any;
}

declare module 'fastify/test/route-prefix.test' {
  declare module.exports: any;
}

declare module 'fastify/test/route.test' {
  declare module.exports: any;
}

declare module 'fastify/test/router-options.test' {
  declare module.exports: any;
}

declare module 'fastify/test/shared-schemas.test' {
  declare module.exports: any;
}

declare module 'fastify/test/stream.test' {
  declare module.exports: any;
}

declare module 'fastify/test/throw.test' {
  declare module.exports: any;
}

declare module 'fastify/test/versioned-routes.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fastify/examples/asyncawait.js' {
  declare module.exports: $Exports<'fastify/examples/asyncawait'>;
}
declare module 'fastify/examples/example.js' {
  declare module.exports: $Exports<'fastify/examples/example'>;
}
declare module 'fastify/examples/hooks-benchmark-async-await.js' {
  declare module.exports: $Exports<'fastify/examples/hooks-benchmark-async-await'>;
}
declare module 'fastify/examples/hooks-benchmark.js' {
  declare module.exports: $Exports<'fastify/examples/hooks-benchmark'>;
}
declare module 'fastify/examples/hooks.js' {
  declare module.exports: $Exports<'fastify/examples/hooks'>;
}
declare module 'fastify/examples/http2.js' {
  declare module.exports: $Exports<'fastify/examples/http2'>;
}
declare module 'fastify/examples/https.js' {
  declare module.exports: $Exports<'fastify/examples/https'>;
}
declare module 'fastify/examples/middleware.js' {
  declare module.exports: $Exports<'fastify/examples/middleware'>;
}
declare module 'fastify/examples/parser.js' {
  declare module.exports: $Exports<'fastify/examples/parser'>;
}
declare module 'fastify/examples/plugin.js' {
  declare module.exports: $Exports<'fastify/examples/plugin'>;
}
declare module 'fastify/examples/route-prefix.js' {
  declare module.exports: $Exports<'fastify/examples/route-prefix'>;
}
declare module 'fastify/examples/simple.js' {
  declare module.exports: $Exports<'fastify/examples/simple'>;
}
declare module 'fastify/examples/use-plugin.js' {
  declare module.exports: $Exports<'fastify/examples/use-plugin'>;
}
declare module 'fastify/fastify.js' {
  declare module.exports: $Exports<'fastify/fastify'>;
}
declare module 'fastify/lib/ContentTypeParser.js' {
  declare module.exports: $Exports<'fastify/lib/ContentTypeParser'>;
}
declare module 'fastify/lib/decorate.js' {
  declare module.exports: $Exports<'fastify/lib/decorate'>;
}
declare module 'fastify/lib/handleRequest.js' {
  declare module.exports: $Exports<'fastify/lib/handleRequest'>;
}
declare module 'fastify/lib/hookRunner.js' {
  declare module.exports: $Exports<'fastify/lib/hookRunner'>;
}
declare module 'fastify/lib/hooks.js' {
  declare module.exports: $Exports<'fastify/lib/hooks'>;
}
declare module 'fastify/lib/logger.js' {
  declare module.exports: $Exports<'fastify/lib/logger'>;
}
declare module 'fastify/lib/pluginUtils.js' {
  declare module.exports: $Exports<'fastify/lib/pluginUtils'>;
}
declare module 'fastify/lib/reply.js' {
  declare module.exports: $Exports<'fastify/lib/reply'>;
}
declare module 'fastify/lib/request.js' {
  declare module.exports: $Exports<'fastify/lib/request'>;
}
declare module 'fastify/lib/schemas.js' {
  declare module.exports: $Exports<'fastify/lib/schemas'>;
}
declare module 'fastify/lib/validation.js' {
  declare module.exports: $Exports<'fastify/lib/validation'>;
}
declare module 'fastify/test/404s.test.js' {
  declare module.exports: $Exports<'fastify/test/404s.test'>;
}
declare module 'fastify/test/500s.test.js' {
  declare module.exports: $Exports<'fastify/test/500s.test'>;
}
declare module 'fastify/test/async-await.js' {
  declare module.exports: $Exports<'fastify/test/async-await'>;
}
declare module 'fastify/test/async-await.test.js' {
  declare module.exports: $Exports<'fastify/test/async-await.test'>;
}
declare module 'fastify/test/beforeHandler.test.js' {
  declare module.exports: $Exports<'fastify/test/beforeHandler.test'>;
}
declare module 'fastify/test/bodyLimit.test.js' {
  declare module.exports: $Exports<'fastify/test/bodyLimit.test'>;
}
declare module 'fastify/test/case-insensitive.test.js' {
  declare module.exports: $Exports<'fastify/test/case-insensitive.test'>;
}
declare module 'fastify/test/chainable.test.js' {
  declare module.exports: $Exports<'fastify/test/chainable.test'>;
}
declare module 'fastify/test/close-pipelining.test.js' {
  declare module.exports: $Exports<'fastify/test/close-pipelining.test'>;
}
declare module 'fastify/test/close.test.js' {
  declare module.exports: $Exports<'fastify/test/close.test'>;
}
declare module 'fastify/test/context-config.test.js' {
  declare module.exports: $Exports<'fastify/test/context-config.test'>;
}
declare module 'fastify/test/custom-http-server.test.js' {
  declare module.exports: $Exports<'fastify/test/custom-http-server.test'>;
}
declare module 'fastify/test/custom-parser-async.js' {
  declare module.exports: $Exports<'fastify/test/custom-parser-async'>;
}
declare module 'fastify/test/custom-parser.test.js' {
  declare module.exports: $Exports<'fastify/test/custom-parser.test'>;
}
declare module 'fastify/test/decorator.test.js' {
  declare module.exports: $Exports<'fastify/test/decorator.test'>;
}
declare module 'fastify/test/delete.test.js' {
  declare module.exports: $Exports<'fastify/test/delete.test'>;
}
declare module 'fastify/test/error-in-post.js' {
  declare module.exports: $Exports<'fastify/test/error-in-post'>;
}
declare module 'fastify/test/fastify-instance.test.js' {
  declare module.exports: $Exports<'fastify/test/fastify-instance.test'>;
}
declare module 'fastify/test/get.test.js' {
  declare module.exports: $Exports<'fastify/test/get.test'>;
}
declare module 'fastify/test/handler-context.test.js' {
  declare module.exports: $Exports<'fastify/test/handler-context.test'>;
}
declare module 'fastify/test/head.test.js' {
  declare module.exports: $Exports<'fastify/test/head.test'>;
}
declare module 'fastify/test/helper.js' {
  declare module.exports: $Exports<'fastify/test/helper'>;
}
declare module 'fastify/test/hooks-async.js' {
  declare module.exports: $Exports<'fastify/test/hooks-async'>;
}
declare module 'fastify/test/hooks.test.js' {
  declare module.exports: $Exports<'fastify/test/hooks.test'>;
}
declare module 'fastify/test/http2/http2.test.js' {
  declare module.exports: $Exports<'fastify/test/http2/http2.test'>;
}
declare module 'fastify/test/http2/plain.js' {
  declare module.exports: $Exports<'fastify/test/http2/plain'>;
}
declare module 'fastify/test/http2/secure-with-fallback.js' {
  declare module.exports: $Exports<'fastify/test/http2/secure-with-fallback'>;
}
declare module 'fastify/test/http2/secure.js' {
  declare module.exports: $Exports<'fastify/test/http2/secure'>;
}
declare module 'fastify/test/http2/unknwon-http-method.js' {
  declare module.exports: $Exports<'fastify/test/http2/unknwon-http-method'>;
}
declare module 'fastify/test/https/custom-https-server.test.js' {
  declare module.exports: $Exports<'fastify/test/https/custom-https-server.test'>;
}
declare module 'fastify/test/https/https.test.js' {
  declare module.exports: $Exports<'fastify/test/https/https.test'>;
}
declare module 'fastify/test/inject.test.js' {
  declare module.exports: $Exports<'fastify/test/inject.test'>;
}
declare module 'fastify/test/input-validation.js' {
  declare module.exports: $Exports<'fastify/test/input-validation'>;
}
declare module 'fastify/test/input-validation.test.js' {
  declare module.exports: $Exports<'fastify/test/input-validation.test'>;
}
declare module 'fastify/test/internals/all.test.js' {
  declare module.exports: $Exports<'fastify/test/internals/all.test'>;
}
declare module 'fastify/test/internals/decorator.test.js' {
  declare module.exports: $Exports<'fastify/test/internals/decorator.test'>;
}
declare module 'fastify/test/internals/handleRequest.test.js' {
  declare module.exports: $Exports<'fastify/test/internals/handleRequest.test'>;
}
declare module 'fastify/test/internals/hookRunner.test.js' {
  declare module.exports: $Exports<'fastify/test/internals/hookRunner.test'>;
}
declare module 'fastify/test/internals/hooks.test.js' {
  declare module.exports: $Exports<'fastify/test/internals/hooks.test'>;
}
declare module 'fastify/test/internals/logger.test.js' {
  declare module.exports: $Exports<'fastify/test/internals/logger.test'>;
}
declare module 'fastify/test/internals/plugin.test.js' {
  declare module.exports: $Exports<'fastify/test/internals/plugin.test'>;
}
declare module 'fastify/test/internals/reply.test.js' {
  declare module.exports: $Exports<'fastify/test/internals/reply.test'>;
}
declare module 'fastify/test/internals/validation.test.js' {
  declare module.exports: $Exports<'fastify/test/internals/validation.test'>;
}
declare module 'fastify/test/listen.test.js' {
  declare module.exports: $Exports<'fastify/test/listen.test'>;
}
declare module 'fastify/test/logger.test.js' {
  declare module.exports: $Exports<'fastify/test/logger.test'>;
}
declare module 'fastify/test/middleware.test.js' {
  declare module.exports: $Exports<'fastify/test/middleware.test'>;
}
declare module 'fastify/test/options.test.js' {
  declare module.exports: $Exports<'fastify/test/options.test'>;
}
declare module 'fastify/test/output-validation.test.js' {
  declare module.exports: $Exports<'fastify/test/output-validation.test'>;
}
declare module 'fastify/test/patch.test.js' {
  declare module.exports: $Exports<'fastify/test/patch.test'>;
}
declare module 'fastify/test/plugin.helper.js' {
  declare module.exports: $Exports<'fastify/test/plugin.helper'>;
}
declare module 'fastify/test/plugin.test.js' {
  declare module.exports: $Exports<'fastify/test/plugin.test'>;
}
declare module 'fastify/test/post.test.js' {
  declare module.exports: $Exports<'fastify/test/post.test'>;
}
declare module 'fastify/test/pretty-print.test.js' {
  declare module.exports: $Exports<'fastify/test/pretty-print.test'>;
}
declare module 'fastify/test/promises.test.js' {
  declare module.exports: $Exports<'fastify/test/promises.test'>;
}
declare module 'fastify/test/put.test.js' {
  declare module.exports: $Exports<'fastify/test/put.test'>;
}
declare module 'fastify/test/register.test.js' {
  declare module.exports: $Exports<'fastify/test/register.test'>;
}
declare module 'fastify/test/reply-error.test.js' {
  declare module.exports: $Exports<'fastify/test/reply-error.test'>;
}
declare module 'fastify/test/route-prefix.test.js' {
  declare module.exports: $Exports<'fastify/test/route-prefix.test'>;
}
declare module 'fastify/test/route.test.js' {
  declare module.exports: $Exports<'fastify/test/route.test'>;
}
declare module 'fastify/test/router-options.test.js' {
  declare module.exports: $Exports<'fastify/test/router-options.test'>;
}
declare module 'fastify/test/shared-schemas.test.js' {
  declare module.exports: $Exports<'fastify/test/shared-schemas.test'>;
}
declare module 'fastify/test/stream.test.js' {
  declare module.exports: $Exports<'fastify/test/stream.test'>;
}
declare module 'fastify/test/throw.test.js' {
  declare module.exports: $Exports<'fastify/test/throw.test'>;
}
declare module 'fastify/test/versioned-routes.test.js' {
  declare module.exports: $Exports<'fastify/test/versioned-routes.test'>;
}
