// flow-typed signature: f62e58e52440950e5261403bc2e8ca6b
// flow-typed version: <<STUB>>/fastify-helmet_v1.0.3/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fastify-helmet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fastify-helmet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fastify-helmet/benchmarks/express' {
  declare module.exports: any;
}

declare module 'fastify-helmet/benchmarks/koa' {
  declare module.exports: any;
}

declare module 'fastify-helmet/example' {
  declare module.exports: any;
}

declare module 'fastify-helmet/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fastify-helmet/benchmarks/express.js' {
  declare module.exports: $Exports<'fastify-helmet/benchmarks/express'>;
}
declare module 'fastify-helmet/benchmarks/koa.js' {
  declare module.exports: $Exports<'fastify-helmet/benchmarks/koa'>;
}
declare module 'fastify-helmet/example.js' {
  declare module.exports: $Exports<'fastify-helmet/example'>;
}
declare module 'fastify-helmet/index' {
  declare module.exports: $Exports<'fastify-helmet'>;
}
declare module 'fastify-helmet/index.js' {
  declare module.exports: $Exports<'fastify-helmet'>;
}
declare module 'fastify-helmet/test.js' {
  declare module.exports: $Exports<'fastify-helmet/test'>;
}
