// flow-typed signature: f7915c63cf5ed39d27d66d6024aab930
// flow-typed version: <<STUB>>/react-search-input_vlatest/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-search-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-search-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-search-input/lib/__tests__/getValuesForKeys.test' {
  declare module.exports: any;
}

declare module 'react-search-input/lib/__tests__/searchStrings.test' {
  declare module.exports: any;
}

declare module 'react-search-input/lib/index' {
  declare module.exports: any;
}

declare module 'react-search-input/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-search-input/lib/__tests__/getValuesForKeys.test.js' {
  declare module.exports: $Exports<'react-search-input/lib/__tests__/getValuesForKeys.test'>;
}
declare module 'react-search-input/lib/__tests__/searchStrings.test.js' {
  declare module.exports: $Exports<'react-search-input/lib/__tests__/searchStrings.test'>;
}
declare module 'react-search-input/lib/index.js' {
  declare module.exports: $Exports<'react-search-input/lib/index'>;
}
declare module 'react-search-input/lib/util.js' {
  declare module.exports: $Exports<'react-search-input/lib/util'>;
}
