// flow-typed signature: 7756f4c2490dc35fdf7ad45c0414e072
// flow-typed version: <<STUB>>/tpl-next-helpers_v^0.1.0/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tpl-next-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tpl-next-helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tpl-next-helpers/config/babel' {
  declare module.exports: any;
}

declare module 'tpl-next-helpers/config/jest' {
  declare module.exports: any;
}

declare module 'tpl-next-helpers/config/next' {
  declare module.exports: any;
}

declare module 'tpl-next-helpers/config/pm2' {
  declare module.exports: any;
}

declare module 'tpl-next-helpers/util/log' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tpl-next-helpers/config/babel.js' {
  declare module.exports: $Exports<'tpl-next-helpers/config/babel'>;
}
declare module 'tpl-next-helpers/config/jest.js' {
  declare module.exports: $Exports<'tpl-next-helpers/config/jest'>;
}
declare module 'tpl-next-helpers/config/next.js' {
  declare module.exports: $Exports<'tpl-next-helpers/config/next'>;
}
declare module 'tpl-next-helpers/config/pm2.js' {
  declare module.exports: $Exports<'tpl-next-helpers/config/pm2'>;
}
declare module 'tpl-next-helpers/index' {
  declare module.exports: $Exports<'tpl-next-helpers'>;
}
declare module 'tpl-next-helpers/index.js' {
  declare module.exports: $Exports<'tpl-next-helpers'>;
}
declare module 'tpl-next-helpers/util/log.js' {
  declare module.exports: $Exports<'tpl-next-helpers/util/log'>;
}
