version: 2
jobs:
  build:
    environment:
      PORT: '3004'
    docker:
      #- image: circleci/node:10-browsers
      - image: circleci/node:10
      #- image: docker:17.05.0-ce-git
    steps:
      #- setup_remote_docker
      - run:
          name: Check GITHUB_TOKEN is set
          command: |
              if [ -z "$GITHUB_TOKEN" ]; then
                echo "GITHUB_TOKEN needs to be defined in project" && exit 1
              fi
              
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: sudo yarn global add tidil

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Yarn install
          command: |
              yarn
      - run:
          name: Working directory info
          command: |
              ls -la
              pwd
      - run:
          name: Set Git Credentials
          command: |
              git config --global user.email "bot@circleci.com"
              git config --global user.name "CircleCI"

      # - run:
      #     name: Initialise DB
      #     command: |
      #         yarn db:migrate
      #         yarn db:seed     
      - run:
          name: Deployment
          command: |
              sh ./node_modules/tpl-next-helpers/util/circleci/default.sh
              

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - edd
                - eddie
                - staging
                - production
